name: chat_server
description: A sample command-line application.
version: 0.0.1
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  chat_proto:
    git:
      url: https://github.com/Shalomka/chat_proto
      ref: main
  objectbox: ^4.0.1
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  lints: ^3.0.0
  objectbox_generator: any
  test: ^1.24.0
